from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('workspace/login/', views.workspace_login, name='workspace_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/hr/', views.hr_dashboard, name='hr_dashboard'),
    path('dashboard/inventory/', views.inventory_dashboard, name='inventory_dashboard'),
    path('dashboard/inventory/purchase-order/pdf/', views.purchase_order_pdf, name='purchase_order_pdf'),
    path('dashboard/sales/', views.sales_dashboard, name='sales_dashboard'),
    path('dashboard/sales/quotation/save/', views.save_quotation, name='save_quotation'),
    path('dashboard/sales/quotation/<int:quotation_id>/json/', views.quotation_json, name='quotation_json'),
    path('dashboard/sales/quotation/<int:quotation_id>/view/', views.view_quotation_pdf, name='view_quotation_pdf'),
    path('dashboard/sales/quotation/<int:quotation_id>/download/', views.download_quotation_pdf, name='download_quotation_pdf'),
    path('dashboard/sales/service-quotation/save/', views.save_service_quotation, name='save_service_quotation'),
    path('dashboard/sales/service-quotation/<int:quotation_id>/json/', views.service_quotation_json, name='service_quotation_json'),
    path('dashboard/sales/service-quotation/<int:quotation_id>/view/', views.view_service_quotation_pdf, name='view_service_quotation_pdf'),
    path('dashboard/sales/service-quotation/<int:quotation_id>/download/', views.download_service_quotation_pdf, name='download_service_quotation_pdf'),
    path('dashboard/sales/documents/save-pdf/', views.save_sales_document_pdf, name='save_sales_document_pdf'),
    path('dashboard/sales/documents/<int:document_id>/view/', views.view_sales_document_pdf, name='view_sales_document_pdf'),
    path('dashboard/sales/documents/<int:document_id>/download/', views.download_sales_document_pdf, name='download_sales_document_pdf'),
    path('dashboard/sales/receipt/<int:order_id>/', views.sales_receipt, name='sales_receipt'),
    path('dashboard/payroll/', views.payroll_dashboard, name='payroll_dashboard'),
    path(
        'dashboard/hr/payroll/<int:run_id>/register.pdf/',
        views.download_payroll_register_pdf,
        name='download_payroll_register_pdf',
    ),
    path(
        'dashboard/hr/payroll/<int:run_id>/register.xlsx/',
        views.download_payroll_register_xlsx,
        name='download_payroll_register_xlsx',
    ),
    path('dashboard/accounting_dashboard/', views.accounting_dashboard, name='accounting_dashboard'),
    path('dashboard/services_dashboard/', views.services_dashboard, name='services_dashboard'),
    path('dashboard/water_billing_dashboard/', views.water_billing_dashboard, name='water_billing_dashboard'),
    path('dashboard/water-billing/export/', views.water_billing_export_csv, name='water_billing_export_csv'),
    path('dashboard/water-billing/weekly-report/print/', views.print_water_weekly_report, name='print_water_weekly_report'),
    path('dashboard/water-billing/bills/print-batch/', views.print_water_bills_batch, name='print_water_bills_batch'),
    path('dashboard/water-billing/bills/<int:bill_id>/', views.view_water_bill, name='view_water_bill'),
    path('dashboard/water-billing/customers/<int:customer_id>/', views.view_water_customer, name='view_water_customer'),
    path(
        'dashboard/water-billing/customers/<int:customer_id>/billing-history/print/',
        views.print_water_customer_billing_history,
        name='print_water_customer_billing_history',
    ),
    path('dashboard/water-billing/readings/<int:reading_id>/preview/', views.view_water_reading_preview, name='view_water_reading_preview'),
    path('dashboard/water-billing/service-contracts/<int:contract_id>/', views.view_water_service_contract, name='view_water_service_contract'),
    path('dashboard/services/repair-reports/create/', views.create_service_repair_report, name='create_service_repair_report'),
    path('dashboard/services/job-orders/create/', views.create_job_order, name='create_job_order'),
    path('dashboard/services/borrow-material/create/', views.create_material_borrow, name='create_material_borrow'),
    path('dashboard/services/official-business/create/', views.create_official_business_form, name='create_official_business_form'),
    path('dashboard/services/official-business/<int:ob_id>/', views.view_official_business_form, name='view_official_business_form'),
    path('dashboard/services/official-business/<int:ob_id>/edit/', views.edit_official_business_form, name='edit_official_business_form'),
    path('dashboard/services/official-business/<int:ob_id>/delete/', views.delete_official_business_form, name='delete_official_business_form'),
    path('dashboard/services/official-business/<int:ob_id>/approve/', views.approve_official_business_form, name='approve_official_business_form'),
    path('dashboard/services/official-business/<int:ob_id>/reject/', views.reject_official_business_form, name='reject_official_business_form'),
    path('dashboard/services/delivery-receipts/create/', views.create_delivery_receipt, name='create_delivery_receipt'),
    path('dashboard/services/delivery-receipts/<int:receipt_id>/', views.view_delivery_receipt, name='view_delivery_receipt'),
    path('dashboard/services/delivery-receipts/<int:receipt_id>/edit/', views.edit_delivery_receipt, name='edit_delivery_receipt'),
    path('dashboard/services/delivery-receipts/<int:receipt_id>/delete/', views.delete_delivery_receipt, name='delete_delivery_receipt'),
    path('dashboard/services/withdrawal-slips/create/', views.create_withdrawal_slip, name='create_withdrawal_slip'),
    path('dashboard/services/withdrawal-slips/<int:slip_id>/', views.view_withdrawal_slip, name='view_withdrawal_slip'),
    path('dashboard/services/withdrawal-slips/<int:slip_id>/edit/', views.edit_withdrawal_slip, name='edit_withdrawal_slip'),
    path('dashboard/services/withdrawal-slips/<int:slip_id>/delete/', views.delete_withdrawal_slip, name='delete_withdrawal_slip'),
    path('dashboard/services/travel-orders/create/', views.create_travel_order_form, name='create_travel_order_form'),
    path('dashboard/services/travel-orders/<int:order_id>/', views.view_travel_order_form, name='view_travel_order_form'),
    path('dashboard/services/travel-orders/<int:order_id>/edit/', views.edit_travel_order_form, name='edit_travel_order_form'),
    path('dashboard/services/travel-orders/<int:order_id>/delete/', views.delete_travel_order_form, name='delete_travel_order_form'),
    path('dashboard/services/repair-reports/<int:report_id>/', views.view_service_repair_report, name='view_service_repair_report'),
    path('dashboard/services/repair-reports/<int:report_id>/edit/', views.edit_service_repair_report, name='edit_service_repair_report'),
    path('dashboard/services/repair-reports/<int:report_id>/delete/', views.delete_service_repair_report, name='delete_service_repair_report'),
    path('dashboard/services/job-orders/<int:order_id>/', views.view_job_order, name='view_job_order'),
    path('dashboard/services/job-orders/<int:order_id>/edit/', views.edit_job_order, name='edit_job_order'),
    path('dashboard/services/job-orders/<int:order_id>/delete/', views.delete_job_order, name='delete_job_order'),
    path('dashboard/services/job-orders/<int:order_id>/idle-periods/add/', views.add_job_order_idle_period, name='add_job_order_idle_period'),
    path('dashboard/services/job-orders/<int:order_id>/idle-periods/<int:period_id>/delete/', views.delete_job_order_idle_period, name='delete_job_order_idle_period'),
    path('dashboard/services/borrow-material/<int:borrow_id>/', views.view_material_borrow, name='view_material_borrow'),
    path('dashboard/services/borrow-material/<int:borrow_id>/edit/', views.edit_material_borrow, name='edit_material_borrow'),
    path('dashboard/services/borrow-material/<int:borrow_id>/delete/', views.delete_material_borrow, name='delete_material_borrow'),
    path('dashboard/services/borrow-material/<int:borrow_id>/return/', views.return_material_borrow, name='return_material_borrow'),
    path('logout/', views.logout_view, name='logout'),
]
