# Generated by Django 6.0.6 on 2026-07-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('picture', models.TextField(blank=True, default='')),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('pcs_per_ctn', models.PositiveIntegerField(default=0)),
                ('carton_size', models.CharField(blank=True, default='', max_length=100)),
                ('net_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
