# Generated by Django 6.0.6 on 2026-07-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_pics/'),
        ),
    ]
