# Generated by Django 6.0.6 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0002_alter_inventoryitem_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='stock_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
