# Generated by Django 6.0.6 on 2026-07-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0004_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='refund_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='refund_status',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
