# Generated by Django 6.0.6 on 2026-07-10 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0009_load_tax_brackets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_quantity', models.PositiveIntegerField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_refunds', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='vicdashboard.salesorder')),
            ],
            options={
                'ordering': ['-refund_date'],
            },
        ),
    ]
