# Generated by Django 6.0.6 on 2026-07-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0010_refundrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'G-Cash'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('account_receivable', 'Account Receivable')], default='cash', max_length=30),
        ),
    ]
