# Generated by Django 6.0.6 on 2026-07-13 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0011_salesorder_customer_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('driver', models.CharField(max_length=100)),
                ('delivered_from', models.CharField(max_length=200)),
                ('delivered_to', models.CharField(max_length=200)),
                ('delivery_number', models.CharField(max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=200)),
                ('quantity_cartons', models.PositiveIntegerField()),
                ('pcs_per_carton', models.PositiveIntegerField()),
                ('cost_per_carton', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vicdashboard.delivery')),
            ],
        ),
    ]
