# Generated by Django 5.2.5 on 2026-07-20 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0012_delivery_deliveryline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=100)),
                ('quotation_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('currency_other', models.CharField(blank=True, default='', max_length=20)),
                ('customer_company', models.CharField(blank=True, default='', max_length=200)),
                ('customer_contact', models.CharField(blank=True, default='', max_length=200)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=255)),
                ('delivery_terms', models.CharField(blank=True, default='', max_length=255)),
                ('warranty', models.CharField(blank=True, default='', max_length=255)),
                ('other_terms', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('prepared_name', models.CharField(blank=True, default='', max_length=200)),
                ('prepared_title', models.CharField(blank=True, default='', max_length=200)),
                ('prepared_signature', models.TextField(blank=True, default='')),
                ('prepared_date', models.DateField(blank=True, null=True)),
                ('approved_signature', models.TextField(blank=True, default='')),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField(default=0)),
                ('product_description', models.TextField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vicdashboard.quotation')),
            ],
            options={
                'ordering': ['item_number'],
            },
        ),
    ]
