# Generated by Django 6.0.6 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('vicdashboard', '0016_drop_quotationline_unit_amount')]

    operations = [
        migrations.CreateModel(
            name='ServiceRepairReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True)), ('report_date', models.DateField()),
                ('customer_name', models.CharField(max_length=200)), ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('contact_number', models.CharField(blank=True, default='', max_length=100)), ('customer_address', models.TextField(blank=True, default='')),
                ('equipment', models.CharField(max_length=200)), ('model_number', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)), ('complaint', models.TextField()),
                ('diagnosis', models.TextField(blank=True, default='')), ('repairs_performed', models.TextField(blank=True, default='')),
                ('parts_used', models.TextField(blank=True, default='')), ('technician', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('released', 'Released')], default='open', max_length=20)),
                ('recommendations', models.TextField(blank=True, default='')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ], options={'ordering': ['-report_date', '-created_at']},
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_order_number', models.CharField(max_length=50, unique=True)), ('job_date', models.DateField()),
                ('customer_name', models.CharField(max_length=200)), ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('contact_number', models.CharField(blank=True, default='', max_length=100)), ('service_location', models.TextField(blank=True, default='')),
                ('scope_of_work', models.TextField()), ('assigned_to', models.CharField(blank=True, default='', max_length=200)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, default='')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ], options={'ordering': ['-job_date', '-created_at']},
        ),
    ]
