# Generated by Django 5.2.5 on 2026-07-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0022_servicequotation_servicequotationline'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='initial_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
