# Generated by Django 5.2.5 on 2026-07-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0026_seed_accounting_workspace_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
