# Generated by Django 5.2.5 on 2026-07-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0027_attendancelog_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialBusinessForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('application_date', models.DateField()),
                ('ob_dates', models.TextField(blank=True, default='', help_text='One OB date per line.')),
                ('destination', models.TextField(blank=True, default='', help_text='OB address / destination.')),
                ('time_departure', models.TimeField(blank=True, null=True)),
                ('time_return', models.TimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, default='')),
                ('prepared_by', models.CharField(blank=True, default='', help_text="Employee's name & signature.", max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-application_date', '-created_at'],
            },
        ),
    ]
