# Generated by Django 5.2.5 on 2026-07-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0029_delivery_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryreceiptline',
            old_name='amount',
            new_name='unit_price',
        ),
    ]
