# Generated by Django 5.2.5 on 2026-07-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0030_delivery_receipt_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('driver_name', models.CharField(max_length=200)),
                ('travel_with', models.TextField(blank=True, default='', help_text='One passenger name per line.')),
                ('destination', models.CharField(blank=True, default='', max_length=300)),
                ('purpose', models.TextField(blank=True, default='')),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('vehicle_plate', models.CharField(blank=True, default='', max_length=200)),
                ('fuel_allowance', models.CharField(blank=True, default='', help_text='PO# / Amount / Liters', max_length=200)),
                ('approved_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-travel_date', '-created_at'],
            },
        ),
    ]
