# Generated by Django 5.2.5 on 2026-07-28 06:10

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0031_travel_order_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('details', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WaterCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('service_address', models.TextField()),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('government', 'Government'), ('industrial', 'Industrial')], default='residential', max_length=20)),
                ('meter_number', models.CharField(max_length=50, unique=True)),
                ('connection_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('billing_period', models.CharField(help_text='e.g. 2026-07', max_length=20)),
                ('previous_reading', models.PositiveIntegerField(default=0)),
                ('current_reading', models.PositiveIntegerField()),
                ('consumption', models.PositiveIntegerField(default=0)),
                ('is_estimated', models.BooleanField(default=False)),
                ('reader_name', models.CharField(blank=True, default='', max_length=200)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='vicdashboard.watercustomer')),
            ],
            options={
                'ordering': ['-reading_date', '-created_at'],
                'unique_together': {('customer', 'billing_period')},
            },
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('billing_period', models.CharField(max_length=20)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('consumption', models.PositiveIntegerField(default=0)),
                ('rate_per_cum', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10)),
                ('consumption_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fixed_charge', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=14)),
                ('environmental_fee', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=14)),
                ('maintenance_fee', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='vicdashboard.watercustomer')),
                ('meter_reading', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='vicdashboard.watermeterreading')),
            ],
            options={
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('online', 'Online Payment'), ('ewallet', 'E-Wallet')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('received_by', models.CharField(blank=True, default='', max_length=200)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vicdashboard.waterbill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vicdashboard.watercustomer')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterServiceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('disconnection', 'Disconnection'), ('reconnection', 'Reconnection')], max_length=20)),
                ('action_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('reconnection_fee', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=14)),
                ('fee_paid', models.BooleanField(default=False)),
                ('performed_by', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_actions', to='vicdashboard.watercustomer')),
            ],
            options={
                'ordering': ['-action_date', '-created_at'],
            },
        ),
    ]
