# Generated by Django 5.2.5 on 2026-07-30 02:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0033_seed_water_billing_workspace_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='rate_per_cum',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10),
        ),
    ]
