# Generated by Django 5.2.5 on 2026-07-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0034_water_bill_rate_20'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='installment_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='previous_bill_unpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='watercustomer',
            name='installment_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='watermeterreading',
            name='installment_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='watermeterreading',
            name='previous_bill_unpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='environmental_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='fixed_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='maintenance_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
