# Generated by Django 5.2.5 on 2026-07-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0035_water_bill_statement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash')], default='cash', max_length=20),
        ),
    ]
