# Generated by Django 5.2.5 on 2026-08-01 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0038_water_disconnection_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watercustomer',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.CreateModel(
            name='SalesDocumentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('product_quotation', 'Product Quotation'), ('service_quotation', 'Service Quotation'), ('collection_form', 'Collection Form'), ('ageing_accounts', 'Ageing of Accounts'), ('retention_summary', 'Retention Summary')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='sales_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_document_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
