# Generated by Django 6.0.6 on 2026-08-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0039_sales_document_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdocumentarchive',
            name='document_type',
            field=models.CharField(choices=[('product_quotation', 'Product Quotation'), ('service_quotation', 'Service Quotation'), ('collection_form', 'Collection Form'), ('ageing_accounts', 'Ageing of Accounts'), ('retention_summary', 'Retention Summary'), ('petty_cash', 'Petty Cash / Revolving Fund')], max_length=40),
        ),
    ]
