# Generated by Django 6.0.6 on 2026-08-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0041_attendance_punch_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesheetpunch',
            name='afternoon_in',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancesheetpunch',
            name='afternoon_out',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancesheetpunch',
            name='morning_in',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancesheetpunch',
            name='morning_out',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
