# Generated by Django 5.2.5 on 2026-08-04 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0042_attendance_punch_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='job_orders', to='vicdashboard.employee'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='coverage_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joborder',
            name='coverage_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobOrderIdlePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(choices=[('waiting_materials', 'Waiting for materials'), ('other', 'Other')], default='waiting_materials', max_length=32)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_periods', to='vicdashboard.joborder')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
