# Generated by Django 5.2.5 on 2026-08-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0043_joborder_idle_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=525, help_text='Daily wage used for idle-day waste estimates (default ₱525).', max_digits=12),
        ),
    ]
