# Generated by Django 5.2.5 on 2026-08-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0044_employee_daily_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payperiod',
            name='period_type',
            field=models.CharField(choices=[('semi-monthly', 'Semi-monthly (10th & 25th)'), ('monthly', 'Monthly')], default='semi-monthly', max_length=15),
        ),
    ]
