# Generated by Django 5.2.5 on 2026-08-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0047_rename_department_to_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
    ]
