# Generated by Django 5.2.5 on 2026-08-06 06:47

import django.db.models.deletion
from django.db import migrations, models

SEED_CATEGORIES = [
    'COUPLING',
    'ELBOW',
    'TEE',
    'REDUCING COUPLING',
    'REDUCING TEE',
    'PLUG',
    'MALE ADAPTOR',
    'FEMALE ADAPTOR',
    'MALE ELBOW',
    'FEMALE ELBOW',
    'MALE TEE',
    'FEMALE TEE',
    'RESTRAINT FLANGE ADAPTOR',
    'RESTRAINT COUPLING',
    'SLEEVE TYPE COUPLING',
    'REPAIR CLAMP',
    'WATER PIPES',
    'PE-TECH',
]


def seed_inventory_categories(apps, schema_editor):
    InventoryCategory = apps.get_model('vicdashboard', 'InventoryCategory')
    InventoryItem = apps.get_model('vicdashboard', 'InventoryItem')
    for name in SEED_CATEGORIES:
        InventoryCategory.objects.get_or_create(name=name, parent=None)
    by_name = {
        c.name: c
        for c in InventoryCategory.objects.filter(parent__isnull=True)
    }
    for item in InventoryItem.objects.filter(category__isnull=True).exclude(name=''):
        category = by_name.get(item.name)
        if category:
            item.category = category
            item.save(update_fields=['category'])


def unseed_inventory_categories(apps, schema_editor):
    InventoryCategory = apps.get_model('vicdashboard', 'InventoryCategory')
    InventoryCategory.objects.filter(parent__isnull=True, name__in=SEED_CATEGORIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0048_remove_employee_birth_hire_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vicdashboard.inventorycategory')),
            ],
            options={
                'verbose_name_plural': 'inventory categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='vicdashboard.inventorycategory'),
        ),
        migrations.RunPython(seed_inventory_categories, unseed_inventory_categories),
    ]
