# Generated by Django 6.0.6 on 2026-08-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0056_water_customer_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watercustomer',
            name='service_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
