# Generated by Django 6.0.6 on 2026-08-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0057_water_customer_service_address_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watercustomer',
            name='meter_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='watercustomer',
            constraint=models.UniqueConstraint(condition=models.Q(('meter_number', '—'), _negated=True), fields=('meter_number',), name='uniq_watercustomer_meter_number_except_placeholder'),
        ),
    ]
