# Generated by Django 6.0.6 on 2026-08-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0058_water_meter_placeholder_allow_duplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='consumption',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watermeterreading',
            name='consumption',
            field=models.IntegerField(default=0),
        ),
    ]
