# Generated by Django 6.0.6 on 2026-08-24 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0064_waterpayment_ar_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('prepared_by', models.CharField(blank=True, default='', max_length=200)),
                ('audited_by', models.CharField(blank=True, default='', max_length=200)),
                ('approved_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('week_start', 'week_end'), name='uniq_water_weekly_report_range')],
            },
        ),
        migrations.CreateModel(
            name='WaterWeeklyRefillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('line_date', models.CharField(blank=True, default='', max_length=80)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('explanation', models.CharField(blank=True, default='', max_length=255)),
                ('ref_number', models.CharField(blank=True, default='', max_length=100)),
                ('cash_in_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_lines', to='vicdashboard.waterweeklyreport')),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
    ]
