# Generated by Django 6.0.6 on 2026-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0065_water_weekly_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
