# Generated by Django 6.0.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0066_inventoryitem_product_code_max_length_100'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_number', models.CharField(max_length=50, unique=True)),
                ('slip_date', models.DateField()),
                ('requested_by', models.CharField(max_length=200)),
                ('project_area', models.CharField(blank=True, default='', max_length=200)),
                ('client', models.CharField(blank=True, default='', max_length=200)),
                ('ref_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('prepared_by', models.CharField(blank=True, default='', max_length=200)),
                ('attested_by', models.CharField(blank=True, default='', max_length=200)),
                ('received_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-slip_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalSlipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, default='pcs', max_length=50)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_slip_lines', to='vicdashboard.inventoryitem')),
                ('withdrawal_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vicdashboard.withdrawalslip')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
