# Generated by Django 6.0.6 on 2026-09-02 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0067_withdrawal_slip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=10, unique=True)),
                ('invoice_date', models.DateField()),
                ('sale_type', models.CharField(blank=True, choices=[('cash', 'Cash Sales'), ('charge', 'Charge Sales')], default='', max_length=10)),
                ('registered_name', models.CharField(max_length=200)),
                ('tin', models.CharField(blank=True, default='', max_length=50)),
                ('business_address', models.TextField(blank=True, default='')),
                ('dr_number', models.CharField(blank=True, default='', max_length=100)),
                ('vatable_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('zero_rated_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_exempt_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sales_vat_inclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('less_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_of_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('less_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('add_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('less_withholding_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_amount', models.CharField(blank=True, default='', max_length=200)),
                ('cashier_representative', models.CharField(blank=True, default='', max_length=200)),
                ('sc_pwd_id_no', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vicdashboard.serviceinvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
