# Generated by Django 6.0.6 on 2026-09-02 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0068_service_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeingOfAccountsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ageing_of_accounts_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-as_of_date', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='AgeingOfAccountsLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_date', models.DateField(blank=True, null=True)),
                ('line_date_raw', models.CharField(blank=True, default='', max_length=50)),
                ('customer_name', models.CharField(max_length=300)),
                ('po_number', models.CharField(blank=True, default='', max_length=100)),
                ('agent', models.CharField(blank=True, default='', max_length=100)),
                ('bi_number', models.CharField(blank=True, default='', max_length=100)),
                ('si_number', models.CharField(blank=True, default='', max_length=100)),
                ('cr_number', models.CharField(blank=True, default='', max_length=100)),
                ('ci_number', models.CharField(blank=True, default='', max_length=100)),
                ('ar_number', models.CharField(blank=True, default='', max_length=100)),
                ('dr_number', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_raw', models.CharField(blank=True, default='', max_length=50)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_paid_raw', models.CharField(blank=True, default='', max_length=50)),
                ('paid_items', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vicdashboard.ageingofaccountsreport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
