# Generated by Django 6.0.6 on 2026-09-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0069_ageing_of_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='watercustomer',
            name='previous_unpaid_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
