# Generated by Django 6.0.6 on 2026-09-04 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0070_watercustomer_previous_unpaid_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionSummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('total_trxn_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_retention_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_summary_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-as_of_date', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionSummaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_date_raw', models.CharField(blank=True, default='', max_length=50)),
                ('client_name', models.CharField(max_length=300)),
                ('trxn_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('trxn_amount_raw', models.CharField(blank=True, default='', max_length=50)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_raw', models.CharField(blank=True, default='', max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('flag_red_remarks', models.BooleanField(default=False)),
                ('flag_yellow_client', models.BooleanField(default=False)),
                ('flag_pink_row', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vicdashboard.retentionsummaryreport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
