# Generated by Django 6.0.6 on 2026-09-04 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0071_retention_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repr_number', models.CharField(blank=True, default='', max_length=50)),
                ('report_date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('total_cash_in_bank', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_date', models.DateField(blank=True, null=True)),
                ('line_date_raw', models.CharField(blank=True, default='', max_length=50)),
                ('particulars', models.CharField(blank=True, default='', max_length=300)),
                ('explanation', models.TextField(blank=True, default='')),
                ('tin', models.CharField(blank=True, default='', max_length=100)),
                ('pcv_number', models.CharField(blank=True, default='', max_length=100)),
                ('cash_in_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('input_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fuel', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('lodging', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('meal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('purchases', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('repair', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('freight', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('meeting', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('office', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('communication', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bidding', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fines', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('misc', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vicdashboard.pettycashreport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
