# Generated by Django 6.0.6 on 2026-09-10 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0073_ageing_terms_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterpayment',
            name='purpose',
            field=models.CharField(choices=[('bill', 'Water bill'), ('installation', 'Installation fee')], default='bill', max_length=20),
        ),
        migrations.AlterField(
            model_name='waterpayment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vicdashboard.waterbill'),
        ),
    ]
