# Generated by Django 6.0.6 on 2026-09-18 07:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0084_backfill_registration_installation_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterweeklyreport',
            name='overview_remitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterweeklyreport',
            name='overview_remitted_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='waterweeklyreport',
            name='overview_remitted_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='waterweeklyreport',
            name='overview_remitted_gcash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
