# Generated by developer on 2026-09-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0085_water_weekly_overview_remittance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_number', models.CharField(max_length=50, unique=True)),
                ('voucher_date', models.DateField()),
                ('payee', models.CharField(max_length=300)),
                ('payment_for', models.TextField(blank=True, default='')),
                ('check_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_in_bank', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank', models.CharField(blank=True, default='', max_length=120)),
                ('check_number', models.CharField(blank=True, default='', max_length=60)),
                ('received_by', models.CharField(blank=True, default='', max_length=200)),
                ('signatory_prepared', models.CharField(blank=True, default='Angelmarie M. Dapar', max_length=200)),
                ('signatory_checked', models.CharField(blank=True, default='Ms. Beverly Tan', max_length=200)),
                ('signatory_approved', models.CharField(blank=True, default='Ms. Christine Joy Ilogon', max_length=200)),
                ('signatory_approver', models.CharField(blank=True, default='Engr. Arturo I Davis, PME', max_length=200)),
                ('purchases', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contributions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('misc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_vouchers', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-voucher_date', '-cv_number'],
            },
        ),
        migrations.CreateModel(
            name='CheckVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vicdashboard.checkvoucher')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
