# Generated by developer on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0086_check_voucher'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE vicdashboard_checkvoucher ADD COLUMN IF NOT EXISTS check_date date;',
                    reverse_sql='ALTER TABLE vicdashboard_checkvoucher DROP COLUMN IF EXISTS check_date;',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='checkvoucher',
                    name='check_date',
                    field=models.DateField(blank=True, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='salesdocumentarchive',
            name='document_type',
            field=models.CharField(choices=[('product_quotation', 'Product Quotation'), ('service_quotation', 'Service Quotation'), ('collection_form', 'Collection Form'), ('ageing_accounts', 'Ageing of Accounts'), ('retention_summary', 'Retention Summary'), ('petty_cash', 'Petty Cash / Revolving Fund'), ('check_voucher', 'Check Voucher')], max_length=40),
        ),
    ]
