# Generated by Django 5.2.5 on 2026-09-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicdashboard', '0088_rename_check_voucher_signatories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkvoucher',
            name='signatory_approved',
            field=models.CharField(blank=True, default='Christine Joy', max_length=200),
        ),
        migrations.AlterField(
            model_name='checkvoucher',
            name='signatory_approver',
            field=models.CharField(blank=True, default='Engr. Arturo Davis', max_length=200),
        ),
        migrations.AlterField(
            model_name='checkvoucher',
            name='signatory_checked',
            field=models.CharField(blank=True, default='Beverly', max_length=200),
        ),
        migrations.AlterField(
            model_name='checkvoucher',
            name='signatory_prepared',
            field=models.CharField(blank=True, default='Angel Marie', max_length=200),
        ),
    ]
